### PR TITLE
Update vote.html

### PR DESCRIPTION
**Pull request by WatchGamingVideos**
Just making proper grammar

### CODE REVIEW

**Comment by WaffleCodez** [comment]
you opened a pr for one fucking letter? no.

**Comment by RaZeSloth** [comment]
Could've just pulled it 🙄

**Comment by WaffleCodez** [comment]
shatthefackap

**Comment by RaZeSloth** [comment]
> shatthefackap

Fix it? It is still in the code lmao

**Comment by Shamcord** [comment]
> > shatthefackap
> 
> Fix it? It is still in the code lmao

it's fixed now.

**Comment by RaZeSloth** [comment]
Sure

**Pull request closed without merging**
